# Generated by Django 6.0 on 2025-12-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sulg',
            new_name='slug',
        ),
    ]
