# Generated by Django 6.0 on 2025-12-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(max_length=250),
        ),
    ]
